// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wafar.Infrastructure.Migrations.Data.Migration;

#nullable disable

namespace Wafar.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.MaintenanceService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceServices");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompatibleModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalculatedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte>("CommissionType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("CommissionValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("QRCodeId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CouponId")
                        .IsUnique();

                    b.HasIndex("QRCodeId");

                    b.HasIndex("PartnerId", "Status");

                    b.ToTable("Commissions", (string)null);
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.Property<int>("ScanHistoryId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RewardId");

                    b.HasIndex("ScanHistoryId")
                        .IsUnique();

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.HasIndex("Status", "ExpirationDate");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.CouponUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CouponId")
                        .IsUnique();

                    b.HasIndex("UsedByUserId");

                    b.ToTable("CouponUsages", (string)null);
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.ScanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QRCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QRCodeId", "ScanDate");

                    b.ToTable("ScanHistories", (string)null);
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("CommissionType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DefaultCommissionValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionType = (byte)1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultCommissionValue = 10m,
                            FullName = "Ahmed Marketing",
                            IsActive = true,
                            Phone = "01000000000"
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Qr.QRCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QRCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Devices"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SpareParts"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SocialMedia"
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Qr.QRCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("CommissionType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("CommissionValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentScanCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("QRCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ScanLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.HasIndex("QRCategoryId");

                    b.HasIndex("IsActive", "StartDate", "EndDate");

                    b.ToTable("QRCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "STORE-MAIN-001",
                            CommissionType = (byte)1,
                            CommissionValue = 10m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentScanCount = 0,
                            Description = "QR تجريبي لأغراض الاختبار",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "QR رئيسي - واجهة المحل",
                            PartnerId = 1,
                            QRCategoryId = 5,
                            ScanLimit = 1000,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Rewards.QRCodeReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ProbabilityOverride")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QRCodeId")
                        .HasColumnType("int");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("QRCodeId", "RewardId")
                        .IsUnique();

                    b.ToTable("QRCodeRewards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QRCodeId = 1,
                            RewardId = 1
                        },
                        new
                        {
                            Id = 2,
                            QRCodeId = 1,
                            RewardId = 2
                        },
                        new
                        {
                            Id = 3,
                            QRCodeId = 1,
                            RewardId = 3
                        },
                        new
                        {
                            Id = 4,
                            QRCodeId = 1,
                            RewardId = 4
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Rewards.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccessoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ExpirationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaintenanceServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProbabilityPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RewardCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("RewardName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("RewardType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SparePartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MaintenanceServiceId");

                    b.HasIndex("RewardCategoryId");

                    b.HasIndex("SparePartId");

                    b.ToTable("Rewards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "خصم عند إصلاح أي جهاز",
                            DiscountValue = 10m,
                            ExpirationDays = 7,
                            IsActive = true,
                            ProbabilityPercentage = 40m,
                            RewardCategoryId = 1,
                            RewardName = "خصم 10% على الصيانة",
                            RewardType = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "تركيب اسكرينة حماية مجانًا",
                            ExpirationDays = 14,
                            IsActive = true,
                            ProbabilityPercentage = 20m,
                            RewardCategoryId = 2,
                            RewardName = "اسكرينة مجانية",
                            RewardType = (byte)4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDays = 10,
                            IsActive = true,
                            ProbabilityPercentage = 25m,
                            RewardCategoryId = 3,
                            RewardName = "تنظيف الجهاز مجانًا",
                            RewardType = (byte)8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountValue = 50m,
                            ExpirationDays = 7,
                            IsActive = true,
                            ProbabilityPercentage = 15m,
                            RewardCategoryId = 1,
                            RewardName = "خصم 50 جنيه على أي إكسسوار",
                            RewardType = (byte)2
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Rewards.RewardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RewardCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Discounts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FreeItems"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FreeServices"
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Cashier Test",
                            IsActive = true,
                            PasswordHash = "TEMP_HASH_REPLACE_LATER",
                            RoleId = 2,
                            Username = "cashier1"
                        });
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.Commission", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Coupons.Coupon", "Coupon")
                        .WithOne("Commission")
                        .HasForeignKey("CodeKhasm.Domain.Entities.Coupons.Commission", "CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeKhasm.Domain.Entities.Partner", "Partner")
                        .WithMany("Commissions")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeKhasm.Domain.Entities.Qr.QRCode", "QRCode")
                        .WithMany("Commissions")
                        .HasForeignKey("QRCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Partner");

                    b.Navigation("QRCode");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.Coupon", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Customer", "Customer")
                        .WithMany("Coupons")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Rewards.Reward", "Reward")
                        .WithMany("Coupons")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeKhasm.Domain.Entities.Coupons.ScanHistory", "ScanHistory")
                        .WithOne("Coupon")
                        .HasForeignKey("CodeKhasm.Domain.Entities.Coupons.Coupon", "ScanHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reward");

                    b.Navigation("ScanHistory");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.CouponUsage", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Branch", "Branch")
                        .WithMany("CouponUsages")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Coupons.Coupon", "Coupon")
                        .WithOne("CouponUsage")
                        .HasForeignKey("CodeKhasm.Domain.Entities.Coupons.CouponUsage", "CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeKhasm.Domain.Entities.User", "UsedByUser")
                        .WithMany("CouponUsages")
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Coupon");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.ScanHistory", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Customer", "Customer")
                        .WithMany("ScanHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Qr.QRCode", "QRCode")
                        .WithMany("ScanHistories")
                        .HasForeignKey("QRCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("QRCode");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Qr.QRCode", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Branch", "Branch")
                        .WithMany("QRCodes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Partner", "Partner")
                        .WithMany("QRCodes")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Qr.QRCategory", "QRCategory")
                        .WithMany("QRCodes")
                        .HasForeignKey("QRCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Partner");

                    b.Navigation("QRCategory");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Rewards.QRCodeReward", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Qr.QRCode", "QRCode")
                        .WithMany("QRCodeRewards")
                        .HasForeignKey("QRCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeKhasm.Domain.Entities.Rewards.Reward", "Reward")
                        .WithMany("QRCodeRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QRCode");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Rewards.Reward", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Catalog.Accessory", "Accessory")
                        .WithMany("Rewards")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Catalog.Device", "Device")
                        .WithMany("Rewards")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Catalog.MaintenanceService", "MaintenanceService")
                        .WithMany("Rewards")
                        .HasForeignKey("MaintenanceServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeKhasm.Domain.Entities.Rewards.RewardCategory", "RewardCategory")
                        .WithMany("Rewards")
                        .HasForeignKey("RewardCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeKhasm.Domain.Entities.Catalog.SparePart", "SparePart")
                        .WithMany("Rewards")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Accessory");

                    b.Navigation("Device");

                    b.Navigation("MaintenanceService");

                    b.Navigation("RewardCategory");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.User", b =>
                {
                    b.HasOne("CodeKhasm.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId");

                    b.HasOne("CodeKhasm.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Branch", b =>
                {
                    b.Navigation("CouponUsages");

                    b.Navigation("QRCodes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.Accessory", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.Device", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.MaintenanceService", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Catalog.SparePart", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.Coupon", b =>
                {
                    b.Navigation("Commission");

                    b.Navigation("CouponUsage");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Coupons.ScanHistory", b =>
                {
                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Coupons");

                    b.Navigation("ScanHistories");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Partner", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("QRCodes");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Qr.QRCategory", b =>
                {
                    b.Navigation("QRCodes");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Qr.QRCode", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("QRCodeRewards");

                    b.Navigation("ScanHistories");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Rewards.Reward", b =>
                {
                    b.Navigation("Coupons");

                    b.Navigation("QRCodeRewards");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Rewards.RewardCategory", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodeKhasm.Domain.Entities.User", b =>
                {
                    b.Navigation("CouponUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
